name: venus
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: victronenergy/venus-docker
      options: --cpus 1
    steps:
      - name: Set branch name
        id: set_branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Install more UNIX tools
        run: |
          if which apt > /dev/null
          then
             apt update
             apt -y install wget curl unzip
          elif which opkg > /dev/null
          then
             opkg update
             opkg install wget
             opkg install curl
             opkg install unzip
          else
             echo "W: Tests limited because of non-avail of wget and curl"
          fi
      - name: Set script permissions
        run: chmod +x ./scripts/seuss_install.sh
      - name: Execute Installation under Venus OS
        run: |
          echo pwd
          pwd
          echo ls
          ls
          echo "BRANCH = ${{ env.BRANCH_NAME }}"
          echo seuss_install.sh
          if ./scripts/seuss_install.sh ; then
             echo "[OK]"
          else
             echo "[FAIL]"
             pwd
             HEAD_PATH=$(which head)
             find . | $HEAD_PATH -n 30
             exit 1
          fi
        env:
          github_branch: ${{ env.BRANCH_NAME }}
          NOSUDO: 1
          ACTOR: ${{ github.actor }}
          BRANCH: "dev"
      - name: Execute SEUSS under Venus OS
        run: |
          . /data/seuss/venv/bin/activate && python3 seuss.py
        env:
          TESTRUN: 1
